sudo: required
language: c
services:
- docker
before_install:
- docker pull tg9541/docker-sdcc:V3.8.6
install:
- docker run -v `pwd`:/home tg9541/docker-sdcc:V3.8.6 /bin/sh -c "sdcc --version ;
  sstm8 -version"
script: docker run -v `pwd`:/home tg9541/docker-sdcc:V3.8.6 /bin/sh -c "cd /home &&
  make release"
deploy:
  provider: releases
  api_key:
    secure: XE1B9ZqtFxybsZdsdhRBesMYxpfJ5r5Vc1g2o87SgrYcMLj9NPoaxKcdBwHtL869y4SDHEUmO0oY31qG0Ie2PBtpUTnfhjqqM+uWQjzfOeHGwqHdlcRqawTlDPe7Y43TUAedktuZ1haVVzyCEi2gZj+cqZ6YW28s0uOG/oxvuQyDc52craLK+fEbRhrgMhqlwjz2d4l12gETbgSxcC4lcZZkGg1eSOGN92SNdK+pT04MHprRgw1fX/CCDL/LJqhj9b8r0uBP4IwIc/8dWYLDPAnBqRm0QFiMAl0Hmg4u5hZAgOLp+ZPXLPRRHqm8cPs/M2CMSQ35LK56prFfdgmSE9BJ7TEXzlwt8XbRBWHK0c3EGhNiMM7DvxfmunBG7MRkZ8/0YmFrzzbX2B+jtarIaJ/kQnJ1F1Z3VyL5/CQB8DlkY4V2g3nm8qTbE3W6mjuCCAEc/hzIt/eEQznUTnxkznJrVkFHQu0dDUiOYa/sCxmsChd3AltdKuzOepoWUS3BQAxAYUGeyefNAixsg6WLEsjGwrUiY1jX9TbNHAKxeR65sDF2x9yu1PaatT6J8/5RkYGbsjk/lRFX0RBZY1tJ4jcyJTtNNEhr2gLy6nQSJ4TM9JGJCvwKbZ0zvgzAhvngDfosaqpHoE+xygDEQQcXW/ZG9seJbsoyeub3vEgmCAs=
  file:
    - "out/stm8ef-bin.zip"
    - "out/stm8ef-bin.tgz"
  skip_cleanup: true
  on:
    repo: TG9541/XY-LPWM
